spring:
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://${postgres.url}/${postgres.schema}
    username: ${postgres.username}
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    driver-class-name: org.postgresql.Driver

server:
  port: 8080
  servlet:
    context-path: /api

open-router:
  api:
    key: ${OPEN_ROUTER_API_KEY}