spring:
  profiles:
    active: development
  datasource:
    url: jdbc:postgresql://${postgres.url}/${postgres.schema} #TODO
    username: ${postgres.username}
    password: ${postgres.password}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 8080
  servlet:
    context-path: /api