spring:
  profiles:
    active: ${CONTEXT_PROFILE:development}
  datasource:
    url: ${postgres.url}
    username: ${postgres.username}
    password: ${postgres.password}
    schema: ${postgres.schema}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    driver-class-name: org.postgresql.Driver

  flyway:
    locations:
      - classpath:db/migration

server:
  port: 8080
  servlet:
    context-path: /api

open-router:
  api:
    key: ${OPEN_ROUTER_API_KEY}